{
 "title": "EcoFlow Dashboard v2",
 "description": "EcoFlow dashboard",
 "tags": [
  "ecoflow",
  "electricity",
  "IoT"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "label", "label": "Filter by", "query": { "query": "label_names(ecoflow_online)" } },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecoflow_online,$label)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_stand_by_mode{$label=\"$device\"} or ecoflow_mppt_pow_standby_min{$label=\"$device\"} or ecoflow_pd_standby_min{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "XT60 Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_mppt_x60_chg_type{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "X-Boost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_cfg_ac_xboost{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Input (Hz)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_freq{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Health",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_soh{$label=\"$device\"} or ecoflow_bms_bms_status_soh{$label=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_online{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_f32_show_soc{$label=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{$label=\"$device\"} or ecoflow_bms_master_soc{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Total Output (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_watts_out_sum{$label=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Input (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_watts_in_sum{$label=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_cfg_standby_min{$label=\"$device\"} or ecoflow_mppt_ac_standby_mins{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "DC Charge Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_mppt_cfg_chg_type{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_cycles{$label=\"$device\"} or ecoflow_bms_bms_status_cycles{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Output (Hz)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_freq{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_temp{$label=\"$device\"} or ecoflow_bms_bms_status_temp{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "AC Button",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_cfg_ac_enabled{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Car Button",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_mppt_car_state{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "AC Input (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Solar Input (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_mppt_in_watts{$label=\"$device\", product_name=\"DELTA Pro\"} / 10)or ecoflow_mppt_in_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "LCD Off After",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_lcd_off_sec{$label=\"$device\"} or ecoflow_pd_lcd_off_sec{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_remain_time{$label=\"$device\"}*60"
    }
   ]
  },
  {
   "title": "AC Output (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_output_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Car Output (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_car_watts{$label=\"$device\"} > 0"
    }
   ]
  },
  {
   "title": "Type-C Input (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_typec_cha_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "DC Button",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_dc_out_state{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "USB QC Output (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_qc_usb1_watts{$label=\"$device\"} + ecoflow_pd_qc_usb2_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "USB Output (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_usb1_watts{$label=\"$device\"} + ecoflow_pd_usb2_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Type-C Output (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_typec1_watts{$label=\"$device\"} + ecoflow_pd_typec2_watts{$label=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((ecoflow_bms_master_chg_dsg_state{$label=\"$device\"} == 1) + 1) or ((ecoflow_bms_master_chg_dsg_state{$label=\"$device\"} == 2) - 1) or (ecoflow_bms_master_chg_dsg_state{$label=\"$device\"} == 0)) or ecoflow_bms_ems_status_chg_state{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_inv_out_temp{$label=\"$device\"}",
     "legendFormat": "Inverter (℃)"
    },
    {
     "expr": "ecoflow_mppt_mppt_temp{$label=\"$device\"}",
     "legendFormat": "MPPT (℃)"
    },
    {
     "expr": "ecoflow_inv_dc_in_temp{$label=\"$device\"}",
     "legendFormat": "DC (℃)"
    },
    {
     "expr": "ecoflow_mppt_car_temp{$label=\"$device\"}",
     "legendFormat": "Solar (℃)"
    },
    {
     "expr": "ecoflow_pd_car_temp{$label=\"$device\"}",
     "legendFormat": "Car (℃)"
    },
    {
     "expr": "ecoflow_pd_typec1_temp{$label=\"$device\"}",
     "legendFormat": "Type-C #1 (℃)"
    },
    {
     "expr": "ecoflow_pd_typec2_temp{$label=\"$device\"}",
     "legendFormat": "Type-C #2 (℃)"
    },
    {
     "expr": "ecoflow_mppt_dc24v_temp{$label=\"$device\"}",
     "legendFormat": "DCDC24V (℃)"
    }
   ]
  },
  { "title": "Cumulative Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Charged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_pd_chg_power_ac{$label=\"$device\"} or ecoflow_pd_chg_power_a_c{$label=\"$device\"}) + (ecoflow_pd_chg_power_dc{$label=\"$device\"} or ecoflow_pd_chg_power_d_c{$label=\"$device\"}) + ecoflow_pd_chg_sun_power{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Cumulative AC charged (wall)",
   "type": "stat",
   "description": "Cumulative AC power charged (Wh) (wall socket)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_chg_power_ac{$label=\"$device\"} or ecoflow_pd_chg_power_a_c{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Cumulative DC charged",
   "type": "stat",
   "description": "Cumulative DC power charged (Wh) (adapter)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_chg_power_dc{$label=\"$device\"} or ecoflow_pd_chg_power_d_c{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Cumulative solar charged",
   "type": "stat",
   "description": "Cumulative solar power charged (Wh)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_chg_sun_power{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter use time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_inv_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "USB use time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_usb_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Car use time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_car_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "MPPT use time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_mppt_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Total Discharged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_pd_dsg_power_ac{$label=\"$device\"} or ecoflow_pd_dsg_power_a_c{$label=\"$device\"}) + ((ecoflow_pd_dsg_power_dc{$label=\"$device\"} or ecoflow_pd_dsg_power_d_c{$label=\"$device\"}))"
    }
   ]
  },
  {
   "title": "Cumulative AC discharged",
   "type": "stat",
   "description": "Cumulative AC power discharged (Wh)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_dsg_power_ac{$label=\"$device\"}or ecoflow_pd_dsg_power_a_c{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Cumulative DC discharged",
   "type": "stat",
   "description": "Cumulative DC power discharged (Wh)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_dsg_power_dc{$label=\"$device\"} or ecoflow_pd_dsg_power_d_c{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Estimated solar charged",
   "type": "stat",
   "description": "Cumulative solar power charged (Wh)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_pd_dsg_power_a_c{$label=\"$device\"} + ecoflow_pd_dsg_power_d_c{$label=\"$device\"}) - (ecoflow_pd_chg_power_a_c{$label=\"$device\"} + ecoflow_pd_chg_power_d_c{$label=\"$device\"})"
    }
   ]
  },
  {
   "title": "Type-C use time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_typcc_used_time{$label=\"$device\"} or ecoflow_pd_typec_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "USB QC use time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_usbqc_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "DC charging time (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_pd_dc_in_used_time{$label=\"$device\"}"
    }
   ]
  },
  {
   "title": "Used AC Power (Total)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "delta(ecoflow_pd_dsg_power_ac{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_dsg_power_a_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "AC Discharged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_power_ac{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_chg_power_a_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "AC Charged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_power_dc{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_chg_power_d_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "DC Charged"
    },
    {
     "expr": "delta(ecoflow_pd_dsg_power_dc{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_dsg_power_d_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "DC Discharged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_sun_power{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "Solar Charged"
    }
   ]
  },
  {
   "title": "Used AC Power (Total)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "delta(ecoflow_pd_dsg_power_ac{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_dsg_power_a_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "AC Discharged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_power_ac{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_chg_power_a_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "AC Charged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_power_dc{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_chg_power_d_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "DC Charged"
    },
    {
     "expr": "delta(ecoflow_pd_dsg_power_dc{$label=\"$device\"}[$__interval] offset -$__interval) or delta(ecoflow_pd_dsg_power_d_c{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "DC Discharged"
    },
    {
     "expr": "delta(ecoflow_pd_chg_sun_power{$label=\"$device\"}[$__interval] offset -$__interval)",
     "legendFormat": "Solar Charged"
    }
   ]
  },
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Input (W)",
   "type": "timeseries",
   "description": "Charging power (W)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{$label=\"$device\"}",
     "legendFormat": "Inverter AC (W)"
    },
    {
     "expr": "(ecoflow_mppt_in_watts{$label=\"$device\", product_name=\"DELTA Pro\"} / 10) or ecoflow_mppt_in_watts{$label=\"$device\"}",
     "legendFormat": "Solar (W)"
    },
    {
     "expr": "ecoflow_pd_typec_cha_watts{$label=\"$device\"}",
     "legendFormat": "Type-C (W)"
    }
   ]
  },
  {
   "title": "Output (W)",
   "type": "timeseries",
   "description": "Discharging power (W)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_output_watts{$label=\"$device\"}",
     "legendFormat": "Inverter AC (W)"
    },
    {
     "expr": "ecoflow_mppt_car_out_watts{$label=\"$device\"}",
     "legendFormat": "Car (W)"
    },
    {
     "expr": "ecoflow_mppt_dcdc12v_watts{$label=\"$device\"}",
     "legendFormat": "DC12V30A (W)"
    }
   ]
  },
  {
   "title": "Input (A)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_amp{$label=\"$device\"}",
     "legendFormat": "Inverter AC (A)"
    },
    {
     "expr": "(ecoflow_mppt_in_amp{$label=\"$device\", product_name=\"DELTA Pro\"} * 10) or ecoflow_mppt_in_amp{$label=\"$device\"}",
     "legendFormat": "Solar (A)"
    },
    {
     "expr": "ecoflow_inv_dc_in_amp{$label=\"$device\"}",
     "legendFormat": "DC (A)"
    }
   ]
  },
  {
   "title": "Output (A)",
   "type": "timeseries",
   "description": "Inverter output current (mA)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_amp{$label=\"$device\"}",
     "legendFormat": "Inverter AC (A)"
    },
    {
     "expr": "ecoflow_mppt_car_out_amp{$label=\"$device\"}",
     "legendFormat": "Car (A)"
    },
    {
     "expr": "ecoflow_mppt_dcdc12v_amp{$label=\"$device\"}",
     "legendFormat": "DC12V30A (A)"
    }
   ]
  },
  {
   "title": "Input (V)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_vol{$label=\"$device\"}",
     "legendFormat": "AC Inverter (V)"
    },
    {
     "expr": "(ecoflow_mppt_in_vol{$label=\"$device\", product_name=\"DELTA Pro\"} * 100) or ecoflow_mppt_in_vol{$label=\"$device\"}",
     "legendFormat": "Solar (V)"
    },
    {
     "expr": "ecoflow_inv_dc_in_vol{$label=\"$device\"}",
     "legendFormat": "DC (V)"
    }
   ]
  },
  {
   "title": "Output (V)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_vol{$label=\"$device\"}",
     "legendFormat": "Inverter AC (V)"
    },
    {
     "expr": "ecoflow_mppt_car_out_vol{$label=\"$device\"}",
     "legendFormat": "Car (V)"
    },
    {
     "expr": "ecoflow_mppt_dcdc12v_vol{$label=\"$device\"}",
     "legendFormat": "DC12V30A (V)"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Input (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_input_watts{$label=\"$device\"} or ecoflow_bms_bms_status_input_watts{$label=\"$device\"}",
     "legendFormat": "Battery (W)"
    }
   ]
  },
  {
   "title": "Output (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_output_watts{$label=\"$device\"} or ecoflow_bms_bms_status_output_watts{$label=\"$device\"}",
     "legendFormat": "Battery (W)"
    }
   ]
  },
  {
   "title": "I/O Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_amp{$label=\"$device\"} / 1000 or ecoflow_bms_bms_status_amp{$label=\"$device\"}",
     "legendFormat": "Battery (A)"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "I/O Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ecoflow_ems_chg_vol{$label=\"$device\"} / 1000 or ecoflow_bms_ems_status_chg_vol{$label=\"$device\"}",
     "legendFormat": "Battery (V)"
    },
    {
     "expr": "(ecoflow_bms_master_min_cell_vol{$label=\"$device\"} or ecoflow_bms_bms_status_min_cell_vol{$label=\"$device\"}) / 1000",
     "legendFormat": "MIN Cell (V)"
    },
    {
     "expr": "(ecoflow_bms_master_max_cell_vol{$label=\"$device\"} or ecoflow_bms_bms_status_max_cell_vol{$label=\"$device\"}) / 1000",
     "legendFormat": "MAX Cell (V)"
    },
    {
     "expr": "ecoflow_bms_master_cell_vol{$label=\"$device\"} / 1000",
     "legendFormat": "Cell {{index_0}} (V)"
    }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_soc{$label=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{$label=\"$device\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "ecoflow_ems_max_charge_soc{$label=\"$device\"} or ecoflow_bms_ems_status_max_charge_soc{$label=\"$device\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "ecoflow_ems_min_dsg_soc{$label=\"$device\"} or ecoflow_bms_ems_status_min_dsg_soc{$label=\"$device\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_temp{$label=\"$device\"} or ecoflow_bms_bms_status_temp{$label=\"$device\"}",
     "legendFormat": "Battery (℃)"
    },
    {
     "expr": "ecoflow_bms_bms_status_max_cell_temp{$label=\"$device\"}",
     "legendFormat": "MAX Cell (℃)"
    },
    {
     "expr": "ecoflow_bms_bms_status_min_cell_temp{$label=\"$device\"}",
     "legendFormat": "MIN Cell (℃)"
    },
    {
     "expr": "ecoflow_bms_bms_status_max_mos_temp{$label=\"$device\"}",
     "legendFormat": "MOS MAX Cell (℃)"
    },
    {
     "expr": "ecoflow_bms_bms_status_min_mos_temp{$label=\"$device\"}",
     "legendFormat": "MOS MIN Cell (℃)"
    }
   ]
  },
  {
   "title": "Battery Capacity (A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_design_cap{$label=\"$device\"} or ecoflow_bms_bms_status_design_cap{$label=\"$device\"} ",
     "legendFormat": "Design (A)"
    },
    {
     "expr": "ecoflow_bms_master_full_cap{$label=\"$device\"} or ecoflow_bms_bms_status_full_cap{$label=\"$device\"}",
     "legendFormat": "Full (A)"
    },
    {
     "expr": "ecoflow_bms_master_remain_cap{$label=\"$device\"} or ecoflow_bms_bms_status_remain_cap{$label=\"$device\"}",
     "legendFormat": "Remain (A)"
    }
   ]
  },
  { "title": "USB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Output (W)",
   "type": "timeseries",
   "description": "Discharging power (W)",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_pd_usb1_watts{$label=\"$device\"}",
     "legendFormat": "USB #1 (W)"
    },
    {
     "expr": "ecoflow_pd_usb2_watts{$label=\"$device\"}",
     "legendFormat": "USB #2 (W)"
    },
    {
     "expr": "ecoflow_pd_qc_usb1_watts{$label=\"$device\"}",
     "legendFormat": "USB QC #1 (W)"
    },
    {
     "expr": "ecoflow_pd_qc_usb2_watts{$label=\"$device\"}",
     "legendFormat": "USB QC #2 (W)"
    },
    {
     "expr": "ecoflow_pd_typec1_watts{$label=\"$device\"}",
     "legendFormat": "Type-C #1 (W)"
    },
    {
     "expr": "ecoflow_pd_typec2_watts{$label=\"$device\"}",
     "legendFormat": "Type-C #2 (W)"
    }
   ]
  },
  {
   "title": "Temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_pd_typec1_temp{$label=\"$device\"}",
     "legendFormat": "Type-C #1 (℃)"
    },
    {
     "expr": "ecoflow_pd_typec2_temp{$label=\"$device\"}",
     "legendFormat": "Type-C #2 (℃)"
    }
   ]
  },
  { "title": "MPPT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Solar power",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[$__range]) / (count_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[1m])*60)",
     "legendFormat": "Battery charged"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[$__range]) / (count_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Collected"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[24h]) / (count_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Battery charged (24h)"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[24h]) / (count_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Collected (24h)"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[7d]) / (count_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Battery charged (7d)"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[7d]) / (count_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Collected (7d)"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[30d]) / (count_over_time(ecoflow_mppt_in_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Battery charged (30d)"
    },
    {
     "expr": "sum_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[30d]) / (count_over_time(ecoflow_mppt_out_watts{$label=\"$device\"}[1m]) * 60)",
     "legendFormat": "Collected (30d)"
    }
   ]
  },
  {
   "title": "Solar power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_in_watts{$label=\"$device\"}",
     "legendFormat": "Watts in"
    },
    {
     "expr": "ecoflow_mppt_in_vol{$label=\"$device\"}/1000 * ecoflow_mppt_in_amp{$label=\"$device\"} / 1000",
     "legendFormat": "Watts on panel"
    }
   ]
  },
  {
   "title": "Battery Energy Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol{$label=\"$device\"}/1000 * ecoflow_bms_master_amp{$label=\"$device\"}/1000",
     "legendFormat": "Master BMS"
    },
    {
     "expr": "ecoflow_mppt_in_vol{$label=\"$device\"} / 1000  * ecoflow_mppt_in_amp{$label=\"$device\"} / 1000",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Solar voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_in_vol{$label=\"$device\"}",
     "legendFormat": "Volts in"
    }
   ]
  },
  {
   "title": "Battery Managemant System Power Balance ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_amp{$label=\"$device\"}/1000",
     "legendFormat": "Amp in"
    }
   ]
  },
  {
   "title": "Solar current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_mppt_in_amp{$label=\"$device\"}",
     "legendFormat": "Amp in"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "MQTT Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "targets": [
    {
     "expr": "increase(ecoflow_connection_errors_total{$label=\"$device\"}[1m])",
     "legendFormat": "MQTT Messages"
    }
   ]
  }
 ]
}